from fastapi import FastAPI
from fastapi.responses import FileResponse
import cv2

app = FastAPI(
    title="Raspberry Pi Camera Service",
    version="0.0.1",
)


@app.get(
    "/image",

    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses = {
        200: {
            "content": {"image/png": {}}
        }
    }
)
async def get_image():
    """Get image from camera"""
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    if ret:
        cv2.imwrite("image.jpg", frame)
    cap.release()

    return FileResponse("image.jpg")